# Generated by Django 5.2.9 on 2025-12-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtext',
            name='text_title',
            field=models.CharField(default='A Day at the Company', max_length=255),
            preserve_default=False,
        ),
    ]
