# Generated by Django 5.2.9 on 2025-12-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_folder_owner_alter_quizscore_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('listening_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vocabulary.listeningquiz')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vocabulary.listeningquestion')),
            ],
        ),
    ]
